apiVersion: v1
kind: Service
metadata:
  name: jmx-exporter
  namespace: monitoring
spec:
  selector:
    app: jmx-exporter
  type: NodePort
  ports:
    - port: 5556
      targetPort: 5556
      nodePort: 31700