apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmx-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmx-exporter
  template:
    metadata:
      labels:
        app: jmx-exporter
    spec:
      containers:
        - name: jmx-exporter
          image: bitnami/jmx-exporter:latest
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: jmx-exporter-config
              mountPath: /etc/jmx-exporter
      volumes:
        - name: jmx-exporter-config
          configMap:
            name: jmx-exporter-config